/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1CollectionsIdGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "collection")]
    pub collection: Box<models::Collection>,
    #[serde(rename = "modules")]
    pub modules: Vec<models::CollectionModule>,
}

impl ApiV1CollectionsIdGet200Response {
    pub fn new(version: i32, collection: models::Collection, modules: Vec<models::CollectionModule>) -> ApiV1CollectionsIdGet200Response {
        ApiV1CollectionsIdGet200Response {
            version,
            collection: Box::new(collection),
            modules,
        }
    }
}

