/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1ModulesPost200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl ApiV1ModulesPost200Response {
    pub fn new(version: i32, uuid: String, message: String) -> ApiV1ModulesPost200Response {
        ApiV1ModulesPost200Response {
            version,
            uuid,
            message,
        }
    }
}

