/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1ModulesUuidScreenshotsGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "screenshots")]
    pub screenshots: Vec<models::Screenshot>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ApiV1ModulesUuidScreenshotsGet200Response {
    pub fn new(version: i32, screenshots: Vec<models::Screenshot>, total: i32) -> ApiV1ModulesUuidScreenshotsGet200Response {
        ApiV1ModulesUuidScreenshotsGet200Response {
            version,
            screenshots,
            total,
        }
    }
}

