/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1AdminUsersIdVerifyPost200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "user_id")]
    pub user_id: i64,
    #[serde(rename = "verified_author")]
    pub verified_author: bool,
}

impl ApiV1AdminUsersIdVerifyPost200Response {
    pub fn new(
        version: i32,
        user_id: i64,
        verified_author: bool,
    ) -> ApiV1AdminUsersIdVerifyPost200Response {
        ApiV1AdminUsersIdVerifyPost200Response {
            version,
            user_id,
            verified_author,
        }
    }
}
