/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1ModulesGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "modules")]
    pub modules: Vec<models::RegistryModule>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ApiV1ModulesGet200Response {
    pub fn new(version: i32, modules: Vec<models::RegistryModule>, total: i32) -> ApiV1ModulesGet200Response {
        ApiV1ModulesGet200Response {
            version,
            modules,
            total,
        }
    }
}

