/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1NotificationsGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "notifications")]
    pub notifications: Vec<models::Notification>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ApiV1NotificationsGet200Response {
    pub fn new(
        version: i32,
        notifications: Vec<models::Notification>,
        total: i32,
    ) -> ApiV1NotificationsGet200Response {
        ApiV1NotificationsGet200Response {
            version,
            notifications,
            total,
        }
    }
}
