/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1FeaturedGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "featured")]
    pub featured: Vec<models::RegistryModule>,
    #[serde(rename = "popular")]
    pub popular: Vec<models::RegistryModule>,
    #[serde(rename = "recent")]
    pub recent: Vec<models::RegistryModule>,
}

impl ApiV1FeaturedGet200Response {
    pub fn new(version: i32, featured: Vec<models::RegistryModule>, popular: Vec<models::RegistryModule>, recent: Vec<models::RegistryModule>) -> ApiV1FeaturedGet200Response {
        ApiV1FeaturedGet200Response {
            version,
            featured,
            popular,
            recent,
        }
    }
}

