/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1AdminStatsGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "total_modules")]
    pub total_modules: i64,
    #[serde(rename = "total_users")]
    pub total_users: i64,
    #[serde(rename = "total_downloads")]
    pub total_downloads: i64,
    #[serde(rename = "pending_submissions")]
    pub pending_submissions: i64,
}

impl ApiV1AdminStatsGet200Response {
    pub fn new(
        version: i32,
        total_modules: i64,
        total_users: i64,
        total_downloads: i64,
        pending_submissions: i64,
    ) -> ApiV1AdminStatsGet200Response {
        ApiV1AdminStatsGet200Response {
            version,
            total_modules,
            total_users,
            total_downloads,
            pending_submissions,
        }
    }
}
