/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1CategoriesGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "categories")]
    pub categories: Vec<models::CategoryInfo>,
}

impl ApiV1CategoriesGet200Response {
    pub fn new(version: i32, categories: Vec<models::CategoryInfo>) -> ApiV1CategoriesGet200Response {
        ApiV1CategoriesGet200Response {
            version,
            categories,
        }
    }
}

