/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1UsersMeGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "avatar_url", skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<String>,
    #[serde(rename = "bio", skip_serializing_if = "Option::is_none")]
    pub bio: Option<String>,
    #[serde(rename = "website_url", skip_serializing_if = "Option::is_none")]
    pub website_url: Option<String>,
    #[serde(rename = "github_url", skip_serializing_if = "Option::is_none")]
    pub github_url: Option<String>,
    #[serde(rename = "twitter_url", skip_serializing_if = "Option::is_none")]
    pub twitter_url: Option<String>,
    #[serde(rename = "bluesky_url", skip_serializing_if = "Option::is_none")]
    pub bluesky_url: Option<String>,
    #[serde(rename = "discord_url", skip_serializing_if = "Option::is_none")]
    pub discord_url: Option<String>,
    #[serde(rename = "sponsor_url", skip_serializing_if = "Option::is_none")]
    pub sponsor_url: Option<String>,
    #[serde(rename = "verified_author")]
    pub verified_author: bool,
    #[serde(rename = "role")]
    pub role: models::UserRole,
    #[serde(rename = "module_count")]
    pub module_count: i64,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl ApiV1UsersMeGet200Response {
    pub fn new(version: i32, id: i64, username: String, verified_author: bool, role: models::UserRole, module_count: i64, created_at: String) -> ApiV1UsersMeGet200Response {
        ApiV1UsersMeGet200Response {
            version,
            id,
            username,
            display_name: None,
            avatar_url: None,
            bio: None,
            website_url: None,
            github_url: None,
            twitter_url: None,
            bluesky_url: None,
            discord_url: None,
            sponsor_url: None,
            verified_author,
            role,
            module_count,
            created_at,
        }
    }
}

