/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddModuleRequest {
    #[serde(rename = "module_uuid")]
    pub module_uuid: String,
    #[serde(rename = "note", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub note: Option<Option<String>>,
}

impl AddModuleRequest {
    pub fn new(module_uuid: String) -> AddModuleRequest {
        AddModuleRequest {
            module_uuid,
            note: None,
        }
    }
}

