/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminStats {
    #[serde(rename = "total_modules")]
    pub total_modules: i64,
    #[serde(rename = "total_users")]
    pub total_users: i64,
    #[serde(rename = "total_downloads")]
    pub total_downloads: i64,
    #[serde(rename = "pending_submissions")]
    pub pending_submissions: i64,
}

impl AdminStats {
    pub fn new(total_modules: i64, total_users: i64, total_downloads: i64, pending_submissions: i64) -> AdminStats {
        AdminStats {
            total_modules,
            total_users,
            total_downloads,
            pending_submissions,
        }
    }
}

