/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnouncementResponse {
    #[serde(rename = "sent")]
    pub sent: i32,
}

impl AnnouncementResponse {
    pub fn new(sent: i32) -> AnnouncementResponse {
        AnnouncementResponse {
            sent,
        }
    }
}

