/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1LandingGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "stats")]
    pub stats: Box<models::PublicStats>,
    #[serde(rename = "install_methods")]
    pub install_methods: Vec<models::LandingInstallMethod>,
}

impl ApiV1LandingGet200Response {
    pub fn new(
        version: i32,
        stats: models::PublicStats,
        install_methods: Vec<models::LandingInstallMethod>,
    ) -> ApiV1LandingGet200Response {
        ApiV1LandingGet200Response {
            version,
            stats: Box::new(stats),
            install_methods,
        }
    }
}
