/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1UsersMeDelete200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "message")]
    pub message: String,
}

impl ApiV1UsersMeDelete200Response {
    pub fn new(version: i32, message: String) -> ApiV1UsersMeDelete200Response {
        ApiV1UsersMeDelete200Response { version, message }
    }
}
