/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1NotificationsAnnouncementsPost200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "sent")]
    pub sent: i32,
}

impl ApiV1NotificationsAnnouncementsPost200Response {
    pub fn new(version: i32, sent: i32) -> ApiV1NotificationsAnnouncementsPost200Response {
        ApiV1NotificationsAnnouncementsPost200Response {
            version,
            sent,
        }
    }
}

