/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1AdminSubmissionsGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "submissions")]
    pub submissions: Vec<models::Submission>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ApiV1AdminSubmissionsGet200Response {
    pub fn new(
        version: i32,
        submissions: Vec<models::Submission>,
        total: i32,
    ) -> ApiV1AdminSubmissionsGet200Response {
        ApiV1AdminSubmissionsGet200Response {
            version,
            submissions,
            total,
        }
    }
}
