/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1NotificationsIdReadPatch200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "success")]
    pub success: bool,
}

impl ApiV1NotificationsIdReadPatch200Response {
    pub fn new(version: i32, success: bool) -> ApiV1NotificationsIdReadPatch200Response {
        ApiV1NotificationsIdReadPatch200Response {
            version,
            success,
        }
    }
}

