/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1CollectionsPost200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "message")]
    pub message: String,
}

impl ApiV1CollectionsPost200Response {
    pub fn new(version: i32, id: i64, message: String) -> ApiV1CollectionsPost200Response {
        ApiV1CollectionsPost200Response {
            version,
            id,
            message,
        }
    }
}

