/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1NotificationsUnreadCountGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "unread_count")]
    pub unread_count: i64,
}

impl ApiV1NotificationsUnreadCountGet200Response {
    pub fn new(version: i32, unread_count: i64) -> ApiV1NotificationsUnreadCountGet200Response {
        ApiV1NotificationsUnreadCountGet200Response {
            version,
            unread_count,
        }
    }
}

