/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1CollectionsGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "collections")]
    pub collections: Vec<models::Collection>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ApiV1CollectionsGet200Response {
    pub fn new(version: i32, collections: Vec<models::Collection>, total: i32) -> ApiV1CollectionsGet200Response {
        ApiV1CollectionsGet200Response {
            version,
            collections,
            total,
        }
    }
}

