/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1ModulesUuidVersionsGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "versions")]
    pub versions: Vec<models::VersionHistoryEntry>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ApiV1ModulesUuidVersionsGet200Response {
    pub fn new(version: i32, versions: Vec<models::VersionHistoryEntry>, total: i32) -> ApiV1ModulesUuidVersionsGet200Response {
        ApiV1ModulesUuidVersionsGet200Response {
            version,
            versions,
            total,
        }
    }
}

