/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1NotificationsMarkAllReadPost200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "marked_count")]
    pub marked_count: i64,
}

impl ApiV1NotificationsMarkAllReadPost200Response {
    pub fn new(version: i32, marked_count: i64) -> ApiV1NotificationsMarkAllReadPost200Response {
        ApiV1NotificationsMarkAllReadPost200Response {
            version,
            marked_count,
        }
    }
}
