/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiVersion {
    #[serde(rename = "version")]
    pub version: i32,
}

impl ApiVersion {
    pub fn new(version: i32) -> ApiVersion {
        ApiVersion {
            version,
        }
    }
}

