/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1ModulesUuidReviewsGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "reviews")]
    pub reviews: Vec<models::Review>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ApiV1ModulesUuidReviewsGet200Response {
    pub fn new(
        version: i32,
        reviews: Vec<models::Review>,
        total: i32,
    ) -> ApiV1ModulesUuidReviewsGet200Response {
        ApiV1ModulesUuidReviewsGet200Response {
            version,
            reviews,
            total,
        }
    }
}
