/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1ModulesUuidVersionsVersionUploadPost200Response {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "r2_key")]
    pub r2_key: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl ApiV1ModulesUuidVersionsVersionUploadPost200Response {
    pub fn new(
        version: String,
        uuid: String,
        r2_key: String,
        message: String,
    ) -> ApiV1ModulesUuidVersionsVersionUploadPost200Response {
        ApiV1ModulesUuidVersionsVersionUploadPost200Response {
            version,
            uuid,
            r2_key,
            message,
        }
    }
}
