/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1ModulesUuidStarGet200Response {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "starred")]
    pub starred: bool,
    #[serde(rename = "star_count")]
    pub star_count: i64,
}

impl ApiV1ModulesUuidStarGet200Response {
    pub fn new(version: i32, starred: bool, star_count: i64) -> ApiV1ModulesUuidStarGet200Response {
        ApiV1ModulesUuidStarGet200Response {
            version,
            starred,
            star_count,
        }
    }
}

