/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthSyncResponse {
    #[serde(rename = "user_id")]
    pub user_id: i64,
    #[serde(rename = "username")]
    pub username: String,
}

impl AuthSyncResponse {
    pub fn new(user_id: i64, username: String) -> AuthSyncResponse {
        AuthSyncResponse { user_id, username }
    }
}
