/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthVerifyResponse {
    #[serde(rename = "authenticated")]
    pub authenticated: bool,
    #[serde(
        rename = "github_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub github_id: Option<Option<i64>>,
    #[serde(
        rename = "github_login",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub github_login: Option<Option<String>>,
    #[serde(
        rename = "user_in_db",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_in_db: Option<Option<bool>>,
    #[serde(
        rename = "db_user_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub db_user_id: Option<Option<i64>>,
    #[serde(
        rename = "reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reason: Option<Option<String>>,
}

impl AuthVerifyResponse {
    pub fn new(authenticated: bool) -> AuthVerifyResponse {
        AuthVerifyResponse {
            authenticated,
            github_id: None,
            github_login: None,
            user_in_db: None,
            db_user_id: None,
            reason: None,
        }
    }
}
