/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorProfile {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(
        rename = "display_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    #[serde(
        rename = "avatar_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub avatar_url: Option<Option<String>>,
    #[serde(
        rename = "bio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bio: Option<Option<String>>,
    #[serde(
        rename = "website_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub website_url: Option<Option<String>>,
    #[serde(rename = "verified_author")]
    pub verified_author: bool,
    #[serde(rename = "module_count")]
    pub module_count: i64,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modules")]
    pub modules: Vec<models::RegistryModule>,
}

impl AuthorProfile {
    pub fn new(
        id: i64,
        username: String,
        verified_author: bool,
        module_count: i64,
        created_at: String,
        modules: Vec<models::RegistryModule>,
    ) -> AuthorProfile {
        AuthorProfile {
            id,
            username,
            display_name: None,
            avatar_url: None,
            bio: None,
            website_url: None,
            verified_author,
            module_count,
            created_at,
            modules,
        }
    }
}
