/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoriesResponse {
    #[serde(rename = "categories")]
    pub categories: Vec<models::CategoryInfo>,
}

impl CategoriesResponse {
    pub fn new(categories: Vec<models::CategoryInfo>) -> CategoriesResponse {
        CategoriesResponse {
            categories,
        }
    }
}

