/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionsResponse {
    #[serde(rename = "collections")]
    pub collections: Vec<models::Collection>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl CollectionsResponse {
    pub fn new(collections: Vec<models::Collection>, total: i32) -> CollectionsResponse {
        CollectionsResponse {
            collections,
            total,
        }
    }
}

