/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionModule {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "author")]
    pub author: String,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(
        rename = "note",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub note: Option<Option<String>>,
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "added_at")]
    pub added_at: String,
}

impl CollectionModule {
    pub fn new(
        uuid: String,
        name: String,
        author: String,
        category: String,
        position: i32,
        added_at: String,
    ) -> CollectionModule {
        CollectionModule {
            uuid,
            name,
            author,
            category,
            note: None,
            position,
            added_at,
        }
    }
}
