/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionCreateResponse {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "message")]
    pub message: String,
}

impl CollectionCreateResponse {
    pub fn new(id: i64, message: String) -> CollectionCreateResponse {
        CollectionCreateResponse {
            id,
            message,
        }
    }
}

