/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Collection {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "user_id")]
    pub user_id: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "visibility")]
    pub visibility: String,
    #[serde(rename = "module_count")]
    pub module_count: i64,
    #[serde(rename = "owner")]
    pub owner: Box<models::CollectionOwner>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Collection {
    pub fn new(
        id: i64,
        user_id: i64,
        name: String,
        visibility: String,
        module_count: i64,
        owner: models::CollectionOwner,
        created_at: String,
        updated_at: String,
    ) -> Collection {
        Collection {
            id,
            user_id,
            name,
            description: None,
            visibility,
            module_count,
            owner: Box::new(owner),
            created_at,
            updated_at,
        }
    }
}
