/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionDetailResponse {
    #[serde(rename = "collection")]
    pub collection: Box<models::Collection>,
    #[serde(rename = "modules")]
    pub modules: Vec<models::CollectionModule>,
}

impl CollectionDetailResponse {
    pub fn new(collection: models::Collection, modules: Vec<models::CollectionModule>) -> CollectionDetailResponse {
        CollectionDetailResponse {
            collection: Box::new(collection),
            modules,
        }
    }
}

