/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateModuleRequest {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "category")]
    pub category: String,
    /// HTTPS repository URL.
    #[serde(rename = "repo_url")]
    pub repo_url: String,
    #[serde(rename = "license")]
    pub license: String,
}

impl CreateModuleRequest {
    pub fn new(
        uuid: String,
        name: String,
        description: String,
        category: String,
        repo_url: String,
        license: String,
    ) -> CreateModuleRequest {
        CreateModuleRequest {
            uuid,
            name,
            description,
            category,
            repo_url,
            license,
        }
    }
}
