/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateModuleResponse {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl CreateModuleResponse {
    pub fn new(uuid: String, message: String) -> CreateModuleResponse {
        CreateModuleResponse {
            uuid,
            message,
        }
    }
}

