/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LandingData {
    #[serde(rename = "stats")]
    pub stats: Box<models::PublicStats>,
    #[serde(rename = "install_methods")]
    pub install_methods: Vec<models::LandingInstallMethod>,
}

impl LandingData {
    pub fn new(
        stats: models::PublicStats,
        install_methods: Vec<models::LandingInstallMethod>,
    ) -> LandingData {
        LandingData {
            stats: Box::new(stats),
            install_methods,
        }
    }
}
