/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LandingInstallMethod {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "commands")]
    pub commands: Vec<String>,
}

impl LandingInstallMethod {
    pub fn new(
        id: String,
        label: String,
        description: String,
        commands: Vec<String>,
    ) -> LandingInstallMethod {
        LandingInstallMethod {
            id,
            label,
            description,
            commands,
        }
    }
}
