/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkAllReadResponse {
    #[serde(rename = "marked_count")]
    pub marked_count: i64,
}

impl MarkAllReadResponse {
    pub fn new(marked_count: i64) -> MarkAllReadResponse {
        MarkAllReadResponse {
            marked_count,
        }
    }
}

