/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkReadResponse {
    #[serde(rename = "success")]
    pub success: bool,
}

impl MarkReadResponse {
    pub fn new(success: bool) -> MarkReadResponse {
        MarkReadResponse {
            success,
        }
    }
}

