/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModulesResponse {
    #[serde(rename = "modules")]
    pub modules: Vec<models::RegistryModule>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ModulesResponse {
    pub fn new(modules: Vec<models::RegistryModule>, total: i32) -> ModulesResponse {
        ModulesResponse { modules, total }
    }
}
