/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default)]
pub enum ModuleCategory {
    #[default]
    #[serde(rename = "system")]
    System,
    #[serde(rename = "hardware")]
    Hardware,
    #[serde(rename = "network")]
    Network,
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "power")]
    Power,
    #[serde(rename = "time")]
    Time,
    #[serde(rename = "workspace")]
    Workspace,
    #[serde(rename = "window")]
    Window,
    #[serde(rename = "tray")]
    Tray,
    #[serde(rename = "weather")]
    Weather,
    #[serde(rename = "productivity")]
    Productivity,
    #[serde(rename = "media")]
    Media,
    #[serde(rename = "custom")]
    Custom,

}

impl std::fmt::Display for ModuleCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::System => write!(f, "system"),
            Self::Hardware => write!(f, "hardware"),
            Self::Network => write!(f, "network"),
            Self::Audio => write!(f, "audio"),
            Self::Power => write!(f, "power"),
            Self::Time => write!(f, "time"),
            Self::Workspace => write!(f, "workspace"),
            Self::Window => write!(f, "window"),
            Self::Tray => write!(f, "tray"),
            Self::Weather => write!(f, "weather"),
            Self::Productivity => write!(f, "productivity"),
            Self::Media => write!(f, "media"),
            Self::Custom => write!(f, "custom"),
        }
    }
}


