/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsResponse {
    #[serde(rename = "notifications")]
    pub notifications: Vec<models::Notification>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl NotificationsResponse {
    pub fn new(notifications: Vec<models::Notification>, total: i32) -> NotificationsResponse {
        NotificationsResponse {
            notifications,
            total,
        }
    }
}
