/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationPreferences {
    #[serde(rename = "downloads_enabled")]
    pub downloads_enabled: bool,
    #[serde(rename = "comments_enabled")]
    pub comments_enabled: bool,
    #[serde(rename = "stars_enabled")]
    pub stars_enabled: bool,
    #[serde(rename = "updates_enabled")]
    pub updates_enabled: bool,
    #[serde(rename = "announcements_enabled")]
    pub announcements_enabled: bool,
    #[serde(rename = "email_downloads")]
    pub email_downloads: bool,
    #[serde(rename = "email_comments")]
    pub email_comments: bool,
    #[serde(rename = "email_stars")]
    pub email_stars: bool,
    #[serde(rename = "email_updates")]
    pub email_updates: bool,
    #[serde(rename = "email_announcements")]
    pub email_announcements: bool,
}

impl NotificationPreferences {
    pub fn new(
        downloads_enabled: bool,
        comments_enabled: bool,
        stars_enabled: bool,
        updates_enabled: bool,
        announcements_enabled: bool,
        email_downloads: bool,
        email_comments: bool,
        email_stars: bool,
        email_updates: bool,
        email_announcements: bool,
    ) -> NotificationPreferences {
        NotificationPreferences {
            downloads_enabled,
            comments_enabled,
            stars_enabled,
            updates_enabled,
            announcements_enabled,
            email_downloads,
            email_comments,
            email_stars,
            email_updates,
            email_announcements,
        }
    }
}
