/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Notification {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "notification_type")]
    pub notification_type: NotificationType,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(
        rename = "body",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub body: Option<Option<String>>,
    #[serde(
        rename = "action_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub action_url: Option<Option<String>>,
    #[serde(rename = "is_read")]
    pub is_read: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Notification {
    pub fn new(
        id: i64,
        notification_type: NotificationType,
        title: String,
        is_read: bool,
        created_at: String,
    ) -> Notification {
        Notification {
            id,
            notification_type,
            title,
            body: None,
            action_url: None,
            is_read,
            created_at,
        }
    }
}
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum NotificationType {
    #[default]
    #[serde(rename = "downloads")]
    Downloads,
    #[serde(rename = "comments")]
    Comments,
    #[serde(rename = "stars")]
    Stars,
    #[serde(rename = "updates")]
    Updates,
    #[serde(rename = "announcements")]
    Announcements,
}
