/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProblemDetails : RFC 9457 Problem Details error response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProblemDetails {
    /// Problem type URI; about:blank indicates no extra semantics beyond the HTTP status.
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "detail")]
    pub detail: String,
    #[serde(rename = "instance", skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// Stable, application-level error code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Opaque identifier for correlating errors in logs.
    #[serde(rename = "error_id", skip_serializing_if = "Option::is_none")]
    pub error_id: Option<String>,
}

impl ProblemDetails {
    /// RFC 9457 Problem Details error response.
    pub fn new(r#type: String, title: String, status: i32, detail: String) -> ProblemDetails {
        ProblemDetails {
            r#type,
            title,
            status,
            detail,
            instance: None,
            code: None,
            error_id: None,
        }
    }
}

