/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicStats {
    #[serde(rename = "total_modules")]
    pub total_modules: i64,
    #[serde(rename = "total_downloads")]
    pub total_downloads: i64,
    #[serde(rename = "total_authors")]
    pub total_authors: i64,
}

impl PublicStats {
    pub fn new(total_modules: i64, total_downloads: i64, total_authors: i64) -> PublicStats {
        PublicStats {
            total_modules,
            total_downloads,
            total_authors,
        }
    }
}
