/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishResponse {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl PublishResponse {
    pub fn new(uuid: String, version: String, message: String) -> PublishResponse {
        PublishResponse {
            uuid,
            version,
            message,
        }
    }
}

