/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistryModule {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "author")]
    pub author: String,
    #[serde(rename = "category")]
    pub category: models::ModuleCategory,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "screenshot", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub screenshot: Option<Option<String>>,
    /// HTTPS repository URL.
    #[serde(rename = "repo_url")]
    pub repo_url: String,
    #[serde(rename = "downloads")]
    pub downloads: i64,
    /// Semantic version string.
    #[serde(rename = "version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub version: Option<Option<String>>,
    #[serde(rename = "last_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<Option<String>>,
    #[serde(rename = "rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Option<f32>>,
    #[serde(rename = "verified_author")]
    pub verified_author: bool,
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "checksum", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<Option<String>>,
    #[serde(rename = "license", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub license: Option<Option<String>>,
}

impl RegistryModule {
    pub fn new(uuid: String, name: String, description: String, author: String, category: models::ModuleCategory, repo_url: String, downloads: i64, verified_author: bool, tags: Vec<String>) -> RegistryModule {
        RegistryModule {
            uuid,
            name,
            description,
            author,
            category,
            icon: None,
            screenshot: None,
            repo_url,
            downloads,
            version: None,
            last_updated: None,
            rating: None,
            verified_author,
            tags,
            checksum: None,
            license: None,
        }
    }
}

