/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistryIndex {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "modules")]
    pub modules: Vec<models::RegistryModule>,
    #[serde(rename = "categories")]
    pub categories: std::collections::HashMap<String, models::CategoryInfo>,
}

impl RegistryIndex {
    pub fn new(
        version: i32,
        modules: Vec<models::RegistryModule>,
        categories: std::collections::HashMap<String, models::CategoryInfo>,
    ) -> RegistryIndex {
        RegistryIndex {
            version,
            modules,
            categories,
        }
    }
}
