/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewUser {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(
        rename = "avatar_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub avatar_url: Option<Option<String>>,
}

impl ReviewUser {
    pub fn new(username: String) -> ReviewUser {
        ReviewUser {
            username,
            avatar_url: None,
        }
    }
}
