/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewsResponse {
    #[serde(rename = "reviews")]
    pub reviews: Vec<models::Review>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ReviewsResponse {
    pub fn new(reviews: Vec<models::Review>, total: i32) -> ReviewsResponse {
        ReviewsResponse {
            reviews,
            total,
        }
    }
}

