/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Review {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "rating")]
    pub rating: i32,
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    #[serde(
        rename = "body",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub body: Option<Option<String>>,
    #[serde(rename = "helpful_count")]
    pub helpful_count: i64,
    #[serde(rename = "user")]
    pub user: Box<models::ReviewUser>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(
        rename = "updated_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_at: Option<Option<String>>,
}

impl Review {
    pub fn new(
        id: i64,
        rating: i32,
        helpful_count: i64,
        user: models::ReviewUser,
        created_at: String,
    ) -> Review {
        Review {
            id,
            rating,
            title: None,
            body: None,
            helpful_count,
            user: Box::new(user),
            created_at,
            updated_at: None,
        }
    }
}
