/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Screenshot {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "r2_key")]
    pub r2_key: String,
    #[serde(rename = "alt_text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alt_text: Option<Option<String>>,
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Screenshot {
    pub fn new(id: i64, r2_key: String, position: i32, created_at: String) -> Screenshot {
        Screenshot {
            id,
            r2_key,
            alt_text: None,
            position,
            created_at,
        }
    }
}

