/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotsResponse {
    #[serde(rename = "screenshots")]
    pub screenshots: Vec<models::Screenshot>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ScreenshotsResponse {
    pub fn new(screenshots: Vec<models::Screenshot>, total: i32) -> ScreenshotsResponse {
        ScreenshotsResponse { screenshots, total }
    }
}
