/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotUploadData {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "r2_key")]
    pub r2_key: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl ScreenshotUploadData {
    pub fn new(id: i64, r2_key: String, url: String) -> ScreenshotUploadData {
        ScreenshotUploadData { id, r2_key, url }
    }
}
