/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotDeleteResponse {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "data")]
    pub data: Box<models::ScreenshotDeleteResponseData>,
}

impl ScreenshotDeleteResponse {
    pub fn new(
        version: i32,
        data: models::ScreenshotDeleteResponseData,
    ) -> ScreenshotDeleteResponse {
        ScreenshotDeleteResponse {
            version,
            data: Box::new(data),
        }
    }
}
