/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotUploadResponse {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "data")]
    pub data: Box<models::ScreenshotUploadData>,
}

impl ScreenshotUploadResponse {
    pub fn new(version: i32, data: models::ScreenshotUploadData) -> ScreenshotUploadResponse {
        ScreenshotUploadResponse {
            version,
            data: Box::new(data),
        }
    }
}

