/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotDeleteResponseData {
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl ScreenshotDeleteResponseData {
    pub fn new(deleted: bool) -> ScreenshotDeleteResponseData {
        ScreenshotDeleteResponseData {
            deleted,
        }
    }
}

