/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityCheckGet200Response {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "revoked")]
    pub revoked: bool,
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
}

impl SecurityCheckGet200Response {
    pub fn new(uuid: String, version: String, revoked: bool) -> SecurityCheckGet200Response {
        SecurityCheckGet200Response {
            uuid,
            version,
            revoked,
            reason: None,
        }
    }
}

