/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StarredModule {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "author")]
    pub author: String,
    #[serde(rename = "category")]
    pub category: models::ModuleCategory,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "screenshot", skip_serializing_if = "Option::is_none")]
    pub screenshot: Option<String>,
    /// HTTPS repository URL.
    #[serde(rename = "repo_url")]
    pub repo_url: String,
    #[serde(rename = "downloads")]
    pub downloads: i64,
    /// Semantic version string.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<f32>,
    #[serde(rename = "verified_author")]
    pub verified_author: bool,
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    #[serde(rename = "starred_at")]
    pub starred_at: String,
}

impl StarredModule {
    pub fn new(
        uuid: String,
        name: String,
        description: String,
        author: String,
        category: models::ModuleCategory,
        repo_url: String,
        downloads: i64,
        verified_author: bool,
        tags: Vec<String>,
        starred_at: String,
    ) -> StarredModule {
        StarredModule {
            uuid,
            name,
            description,
            author,
            category,
            icon: None,
            screenshot: None,
            repo_url,
            downloads,
            version: None,
            last_updated: None,
            rating: None,
            verified_author,
            tags,
            checksum: None,
            license: None,
            starred_at,
        }
    }
}
