/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StarStatusResponse {
    #[serde(rename = "starred")]
    pub starred: bool,
    #[serde(rename = "star_count")]
    pub star_count: i64,
}

impl StarStatusResponse {
    pub fn new(starred: bool, star_count: i64) -> StarStatusResponse {
        StarStatusResponse {
            starred,
            star_count,
        }
    }
}
