/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StarsResponse {
    #[serde(rename = "modules")]
    pub modules: Vec<models::StarredModule>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl StarsResponse {
    pub fn new(modules: Vec<models::StarredModule>, total: i32) -> StarsResponse {
        StarsResponse {
            modules,
            total,
        }
    }
}

