/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Submission {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "submitter_id")]
    pub submitter_id: i64,
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "version")]
    pub version: String,
    /// HTTPS repository URL.
    #[serde(rename = "repo_url")]
    pub repo_url: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "rejection_reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rejection_reason: Option<Option<String>>,
    #[serde(rename = "submitted_at")]
    pub submitted_at: String,
    #[serde(
        rename = "reviewed_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reviewed_at: Option<Option<String>>,
    #[serde(
        rename = "reviewed_by",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reviewed_by: Option<Option<i64>>,
    #[serde(rename = "submitter_username")]
    pub submitter_username: String,
}

impl Submission {
    pub fn new(
        id: i64,
        submitter_id: i64,
        uuid: String,
        name: String,
        description: String,
        category: String,
        version: String,
        repo_url: String,
        status: String,
        submitted_at: String,
        submitter_username: String,
    ) -> Submission {
        Submission {
            id,
            submitter_id,
            uuid,
            name,
            description,
            category,
            version,
            repo_url,
            status,
            rejection_reason: None,
            submitted_at,
            reviewed_at: None,
            reviewed_by: None,
            submitter_username,
        }
    }
}
