/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmissionsResponse {
    #[serde(rename = "submissions")]
    pub submissions: Vec<models::Submission>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl SubmissionsResponse {
    pub fn new(submissions: Vec<models::Submission>, total: i32) -> SubmissionsResponse {
        SubmissionsResponse { submissions, total }
    }
}
