/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncStarsRequest {
    #[serde(rename = "uuids")]
    pub uuids: Vec<String>,
    #[serde(rename = "is_public", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
}

impl SyncStarsRequest {
    pub fn new(uuids: Vec<String>) -> SyncStarsRequest {
        SyncStarsRequest {
            uuids,
            is_public: None,
        }
    }
}
