/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncStarsResponse {
    #[serde(rename = "synced")]
    pub synced: i32,
}

impl SyncStarsResponse {
    pub fn new(synced: i32) -> SyncStarsResponse {
        SyncStarsResponse { synced }
    }
}
