/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnreadCountResponse {
    #[serde(rename = "unread_count")]
    pub unread_count: i64,
}

impl UnreadCountResponse {
    pub fn new(unread_count: i64) -> UnreadCountResponse {
        UnreadCountResponse {
            unread_count,
        }
    }
}

