/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadResponse {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "r2_key")]
    pub r2_key: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl UploadResponse {
    pub fn new(uuid: String, version: String, r2_key: String, message: String) -> UploadResponse {
        UploadResponse {
            uuid,
            version,
            r2_key,
            message,
        }
    }
}
