/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionHistoryEntry {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "changelog", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub changelog: Option<Option<String>>,
    #[serde(rename = "downloads")]
    pub downloads: i64,
    #[serde(rename = "published_at")]
    pub published_at: String,
}

impl VersionHistoryEntry {
    pub fn new(version: String, downloads: i64, published_at: String) -> VersionHistoryEntry {
        VersionHistoryEntry {
            version,
            changelog: None,
            downloads,
            published_at,
        }
    }
}

