/*
 * Barforge Registry API
 *
 * Cloudflare Workers REST API for the Barforge ecosystem.
 *
 * The version of the OpenAPI document: 0.7.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionsResponse {
    #[serde(rename = "versions")]
    pub versions: Vec<models::VersionHistoryEntry>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl VersionsResponse {
    pub fn new(versions: Vec<models::VersionHistoryEntry>, total: i32) -> VersionsResponse {
        VersionsResponse { versions, total }
    }
}
